kind: pipeline
name: default
type: docker

steps:
  - name: hello-world
    image: docker:latest
    commands:
      - echo "Hello World"
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
